---
title: "Schedule"
---

## Unit 1: What is Ancient Language Processing?

+----------+-----------------------------------------------------+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------+
| Date     | **Topic**                                           | **Keywords**                                                                        | **Assignment**                                                                                                                                                                                                                                                              | **Materials**                                                  |
+==========+=====================================================+=====================================================================================+=============================================================================================================================================================================================================================================================================+================================================================+
| 09/04/25 | Brushing-up on your Python                          | Character encoding; Regex; Pandas; Parsing; Functions                               | **Choose one ancient language dataset**: familiarize yourself with the data model, consider how this data model fits with the datasets presented in class. [Remodel your data accordingly]{.underline}. Do not forget collecting metadata as defined in the class examples. | -   Reading:                                                   |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             |                                                                |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             | \*\*\*                                                         |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             |                                                                |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             | -   Notebooks:                                                 |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             |                                                                |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             |     1.  [Colab intro](/notebooks/01_colab_intro.ipynb)         |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             |     2.  [Python brush-up](/notebooks/02_Python_Brush_up.ipynb) |
+----------+-----------------------------------------------------+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------+
| 23/04/25 | Doing Computational Philology: the (ideal) pipeline | research questions; microscope vs macroscope; quantification; large language models | **Explore your dataset**: upload the data into Voyant (or similar programs) or into an LLM and describe it based on distant reading techniques (i.e. quantification). Following this analysis decide where close reading would be necessary.                                | -   Reading:                                                   |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             |                                                                |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             | \*\*\*\*                                                       |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             |                                                                |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             | -   Tools:                                                     |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             |                                                                |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             |     1.  Voyant                                                 |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             |     2.  AntConc                                                |
|          |                                                     |                                                                                     |                                                                                                                                                                                                                                                                             |     3.  LLM (ChatGPT, Claude, Olmoe etc.)                      |
+----------+-----------------------------------------------------+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------+

## Unit 2: Digitization and Annotation

+----------+---------------------------------------------------------+--------------------------+----------------+---------------+
| Date     | **Topic**                                               | **Keywords**             | **Assignment** | **Materials** |
+==========+=========================================================+==========================+================+===============+
| 30/04/25 | Pipeline I: Optical / Handwritten Character Recognition | OCR; HTR; data structure |                |               |
+----------+---------------------------------------------------------+--------------------------+----------------+---------------+
| 07/05/25 | Pipeline II: Annotation (Lemmatization)                 |                          |                |               |
+----------+---------------------------------------------------------+--------------------------+----------------+---------------+

## Unit 3: Operationalization and the Vector Space

+----------+-------------------------------------------------------------------+--------------+----------------+---------------+
| Date     | **Topic**                                                         | **Keywords** | **Assignment** | **Materials** |
+==========+===================================================================+==============+================+===============+
| 14/05/25 | Pipeline III: Operationalization of words I - the vector space    |              |                |               |
+----------+-------------------------------------------------------------------+--------------+----------------+---------------+
| 21/05/25 | Pipeline IV: Operationalization of words II - measuring distances |              |                |               |
+----------+-------------------------------------------------------------------+--------------+----------------+---------------+

## Unit 4: Network Analysis and Visualization

+----------+-------------------------------------------------+--------------+----------------+---------------+
| Date     | **Topic**                                       | **Keywords** | **Assignment** | **Materials** |
+==========+=================================================+==============+================+===============+
| 28/05/25 | Pipeline V: Visualization I - Graph theory      |              |                |               |
+----------+-------------------------------------------------+--------------+----------------+---------------+
| 04/06/25 | Pipeline VI: Visualization II - Network metrics |              |                |               |
+----------+-------------------------------------------------+--------------+----------------+---------------+
| 11/06/25 | Presentation of class projects and feedback     |              |                |               |
+----------+-------------------------------------------------+--------------+----------------+---------------+
